  compilers:
  - compiler:
      spec: gcc@4.8.5
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags:
        cflags: -mrdrnd -fPIC
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: intel@2021.4.0
      paths:
        cc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/intel64/icc
        cxx: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/intel64/icpc
        f77: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/intel64/ifort
        fc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/intel64/ifort
      flags:
        cflags: -O2 -we147 -fPIC
        cxxflags: -O2 -we147 -fPIC
      operating_system: centos7
      target: x86_64
      modules: [devel, gcc/9.]
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: oneapi@2021.4.0
      paths:
        cc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/icx
        cxx: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/icpx
        f77: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/ifx
        fc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/ifx
        f90: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/ifx
      flags:
        cflags: -O2 -we147 -fPIC
        cxxflags: -O2 -we147 -fPIC
      operating_system: centos7
      target: x86_64
      modules: [devel, gcc/9.]
      environment: {}
      extra_rpaths: []

  - compiler:
      spec: gcc@9.1.0
      paths:
        cc: /share/software/user/open/gcc/9.1.0/bin/gcc
        cxx: /share/software/user/open/gcc/9.1.0/bin/g++
        f77: /share/software/user/open/gcc/9.1.0/bin/gfortran
        fc: /share/software/user/open/gcc/9.1.0/bin/gfortran
        cpp: /share/software/user/open/gcc/9.1.0/bin/cpp
      environment: {}
      flags:
        cflags: -O2 -fPIC
        cxxflags: -O2 -fPIC
        fflags: -O2 -fallow-argument-mismatch -fPIC
      operating_system: centos7
      target: x86_64
      modules: [devel, gcc/9.1.0]
      extra_rpaths: []
  - compiler:
      spec: intel@19.0.0.117
      paths:
        cc: /share/software/user/restricted/icc/2019/bin/icc
        cxx: /share/software/user/restricted/icc/2019/bin/icpc
        f77: /share/software/user/restricted/ifort/2019/bin/ifort
        fc: /share/software/user/restricted/ifort/2019/bin/ifort
      flags:
        cflags: -O2 -we147 -fPIC
        cxxflags: -O2 -we147 -fPIC
        fflags: -O2 -fPIC
      operating_system: centos7
      target: x86_64
      modules: [devel, icc/2019, ifort/2019]
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@11.2.0
      paths:
        cc: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/gcc-11.2.0-pjl2s6u6mujagujmbvb2chncwdrgeec6/bin/gcc
        cxx: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/gcc-11.2.0-pjl2s6u6mujagujmbvb2chncwdrgeec6/bin/g++
        f77: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/gcc-11.2.0-pjl2s6u6mujagujmbvb2chncwdrgeec6/bin/gfortran
        fc: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/gcc-11.2.0-pjl2s6u6mujagujmbvb2chncwdrgeec6/bin/gfortran
      flags:
        cflags: -O2 -mrdrnd -fPIC
        cxxflags: -O2 -fPIC
        fflags: -O2 -fallow-argument-mismatch -fPIC
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: intel@2021.2.0
      paths:
        cc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-oneapi-compilers-2021.2.0-jd7px7e7gil7j5fh5ca4duqotxidhukh/compiler/2021.2.0/linux/bin/intel64/icc
        cxx: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-oneapi-compilers-2021.2.0-jd7px7e7gil7j5fh5ca4duqotxidhukh/compiler/2021.2.0/linux/bin/intel64/icpc
        f77: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-oneapi-compilers-2021.2.0-jd7px7e7gil7j5fh5ca4duqotxidhukh/compiler/2021.2.0/linux/bin/intel64/ifort
        fc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-oneapi-compilers-2021.2.0-jd7px7e7gil7j5fh5ca4duqotxidhukh/compiler/2021.2.0/linux/bin/intel64/ifort
      flags:
        cflags: -O2 -we147 -fPIC
        cxxflags: -O2 -we147 -fPIC
        fflags: -O2 -fPIC
      operating_system: centos7
      target: x86_64
      modules: [gcc/9.]
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: oneapi@2021.2.0
      paths:
        cc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-oneapi-compilers-2021.2.0-jd7px7e7gil7j5fh5ca4duqotxidhukh/compiler/2021.2.0/linux/bin/icx
        cxx: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-oneapi-compilers-2021.2.0-jd7px7e7gil7j5fh5ca4duqotxidhukh/compiler/2021.2.0/linux/bin/icpx
        f77: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-oneapi-compilers-2021.2.0-jd7px7e7gil7j5fh5ca4duqotxidhukh/compiler/2021.2.0/linux/bin/ifx
        fc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-oneapi-compilers-2021.2.0-jd7px7e7gil7j5fh5ca4duqotxidhukh/compiler/2021.2.0/linux/bin/ifx
      flags:
        cflags: -O2 -we147 -fPIC
        cxxflags: -O2 -we147 -fPIC
        fflags: -O2 -fPIC
      operating_system: centos7
      target: x86_64
      modules: [devel, gcc/9.]
      environment: {}
      extra_rpaths: []
      
