  packages:
    gcc:
      version: [11.2.0]
      compiler: [gcc@9.1.0]
      target: [x86_64]
      externals:
#      - spec: gcc@11.2.0
#        prefix: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64/gcc-9.1.0/gcc-11.2.0-kjhojkbjplqdocfx2ngybnqicjxhfzhm
#        modules: []
      - spec: gcc@9.1.0
        modules: [devel, gcc/9.1.0]
        buildable: false
      - spec: gcc@8.1.0
        modules: [devel, gcc/8.1.0]
        buildable: false
      - spec: gcc@7.3.0
        modules: [devel, gcc/7.3.0]
        buildable: false
    intel-oneapi-compilers:
      version: [2021.4.0]
      compiler: [gcc@9.1.0]
      target: [x86_64]
#      externals:
#      - spec: intel-oneapi-compilers@2021.4.0
#        prefix: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-zen2/gcc-9.1.0/intel-oneapi-compilers-2021.4.0-56emuishvgppatt46d2xynaeliu4fhmc
#        modules: [devel, gcc/9.1.0]
#        buildable: false
    slurm:
      version: [21.08.4]
      externals:
      - spec: slurm@21.08.4
        prefix: /usr
        buildable: false
#    pkg-config:
#      version: [0.29.2]
#      externals:
#      - spec: pkg-config@0.27.1
#        prefix: /usr
#        target: [zen2, skylake, skylake_avx512, x86_64, x86_64_v3]
#        buildable: true
    cmake:
      version: [3.22.1]
#      externals:
#      - spec: cmake@3.20.3
#        modules: [devel,cmake/3.20.3]
#        buildable: false
    munge:
      version: [0.5.14]
    curl:
      version: [7.80.0]
    numactl:
      version: [2.0.14]
    perl:
      version: [5.34.0]
    findutils:
      version: [4.8.0]
    font-util:
      version: [1.3.2]
    python:
      version: [3.8.11]
    berkeley-db:
      version: [18.1.40]
    gdbm:
      version: [1.18.1]
    readline:
      version: [8.1]
    libdwarf:
      version: [20180129]
    ncurses:
      version: [6.2]
    mpich:
      version: [3.4.2]
      variants: +slurm
    openmpi:
      variants: +pmi +pmix +legacylaunchers schedulers=slurm fabrics=ucx,ofi
      version: [4.1.1]
    ucx:
      version: [1.11.2]
      variants: [+cm +cma +dc +ib-hw-tm +mlx5-dv +rc +thread_multiple +ud]
    proj:
      version: [8.1.0]
    geos:
      version: [3.8.1]
    ascent:
      variants: +python
    binutils:
      version: [2.34]
    boost:
      version: [1.75.0]
      variants: +mpi
    cmake:
      version: [3.21.3] #[3.20.1]
    cuda:
      version: [11.4.0]
    emacs:
      variants: +tls
    fftw:
      version: [3.3.9]
    hdf5:
      variants: ~debug+fortran+hl~java+mpi+shared~szip+threadsafe
      version: [1.10.7]
    netcdf-c:
      version: [4.8.1]
    netcdf-cxx4:
      version: [4.3.1]
    netcdf-cxx:
      version: [4.2]
    netcdf-fortran:
      version: [4.5.3]
    parallel-netcdf:
      version: [1.12.2]
    parallelio:
      variants: +pnetcdf
    paraview:
      version: [5.9.1]
      variants: [+hdf5 +python3]
    petsc:
      variants: +batch +fftw +mpi +openmp
    muparser:
      version: [2.2.6.1]
    maven:
      version: [3.6.3]
    memsurfer:
      version: [1.0]
    swig:
      version: [4.0.2]
    cgal:
      version: [5.0.3]
    gdal:
      version: [3.2.2]
    eigen:
      version: [3.3.9]
    cdo:
      version: [1.9.10]
    vtk:
      version: [9.0.0]
    dealii:
      version: [9.2.0]
    xios:
      version: [2.5]
    libgcrypt:
      version: [1.9.2]
    libiconv:
      version: [1.16]
    libtool:
      version: [2.4.6]
    intel-oneapi-tbb:
      version: [2021.4.0]
    intel-oneapi-mkl:
      version: [2021.4.0]
    intel-oneapi-mpi:
      version: [2021.4.0]
    intel-tbb:
      version: [2021.4.0]
    blitz:
      version: [1.0.2]
    tar:
      version: [1.34]
    m4:
      version: [1.4.19]
    gettext:
      version: [0.21]
    all:
      compiler: []
      variants: build_type=Release +mpi
      providers:
        mpi: [mpich, openmpi, intel-oneapi-mpi]
        blas: [openblas, intel-oneapi-mkl]
        lapack: [openblas, intel-oneapi-mkl]
        scalapack: [netlib-scalapack, intel-oneapi-mkl]
#        gl: [osmesa+opengl]
#        glx: [osmesa+glx]
#        awk: [gawk]
#        elf: [elfutils]
#        fftw-api: [fftw]
#        golang: [gcc]
#        iconv: [libiconv]
#        java: [openjdk]
#        jpeg: [libjpeg-turbo]
#        pil: [py-pillow]
#        pkgconfig: [pkg-config]
#        rpc: [libtirpc]
#        sycl: [hipsycl]
#        szip: [libszip]
#        unwind: [libunwind]
#        yacc: [bison]
#        uuid: [libuuid]
      permissions:
        read: world
        write: user
