  packages:
    slurm:
      version: [21.08.4]
      externals:
      - spec: slurm@21.08.4
        prefix: /usr
    numactl:
      version: [2.0.14]
    perl:
      version: [5.34.0]
    findutils:
      version: [4.8.0]
    font-util:
      version: [1.3.2]
    python:
      version: [3.8.11]
    berkeley-db:
      version: [18.1.40]
    gdbm:
      version: [1.18.1]
    readline:
      version: [8.1]
    libdwarf:
      version: [20180129]
    ncurses:
      version: [6.2]
    petsc:
      version: [3.16.1]
      variants: +batch +fftw  +slurm +mpi +openmp
    mpich:
      version: [3.4.2]
      variants: +slurm
    openmpi:
      variants: +pmi +pmix +legacylaunchers schedulers=slurm fabrics=ucx,ofi
      version: [4.1.1]
    ucx:
      version: [1.11.2]
      variants: [+cm +cma +dc +ib-hw-tm +mlx5-dv +rc +thread_multiple +ud]
    proj:
      version: [8.1.0] #[7.2.1]
    geos:
      version: [3.8.1]
    ascent:
      variants: +python
    binutils:
      version: [2.34]
    boost:
      version: [1.75.0]
    cmake:
      version: [3.21.3] #[3.20.1]
    cuda:
      version: [11.4.0]
    emacs:
      variants: +tls
    fftw:
      version: [3.3.9]
    hdf5:
      variants: ~cxx~debug+fortran+hl~java+mpi+shared~szip+threadsafe
      version: [1.10.7, 1.12.0]
    netcdf-c:
      version: [4.8.1]
    netcdf-cxx4:
      version: [4.3.1]
    netcdf-cxx:
      version: [4.2]
    netcdf-fortran:
      version: [4.5.3]
    parallel-netcdf:
      version: [1.12.2]
    parallelio:
      variants: +pnetcdf
    paraview:
      version: [5.9.1]
      variants: [+hdf5 +python3]
    muparser:
      version: [2.2.6.1]
    maven:
      version: [3.6.3]
    memsurfer:
      version: [1.0]
    swig:
      version: [4.0.2]
    cgal:
      version: [5.0.3]
    gdal:
      version: [3.2.2]
    eigen:
      version: [3.3.9]
    cdo:
      version: [1.9.10]
    vtk:
      version: [9.0.0]
    dealii:
      version: [9.2.0]
    xios:
      version: [2.5]
    libgcrypt:
      version: [1.9.2]
    libtool:
      version: [2.4.6]
    gcc:
      version: [11.2.0]
      compiler: [gcc@4.8.5]
      target: [x86_64_v3]
      buildable: true
      externals:
      - spec: gcc@9.1.0
        modules: [devel, gcc/9.1.0]
        buildable: false
      - spec: gcc@8.1.0
        modules: [devel, gcc/8.1.0]
        buildable: false
      - spec: gcc@7.3.0
        modules: [devel, gcc/7.3.0]
        buildable: false
    intel-oneapi-compilers:
      version: [2021.4.0]
      compiler: [gcc@4.8.5]
      target: [x86_64_v3]
    intel-oneapi-tbb:
      version: [2021.4.0]
    intel-oneapi-mkl:
      version: [2021.4.0]
    intel-oneapi-mpi:
      version: [2021.4.0]
    intel-tbb:
      version: [2021.4.0]
    blitz:
      version: [1.0.2]
    tar:
      version: [1.34]
    m4:
      version: [1.4.19]
    gettext:
      version: [0.21]
    all:
      target: [zen2]
      compiler: [gcc@11.2.0, intel@2021.4.0, oneapi@2021.4.0]
      variants: build_type=Release +mpi
      providers:
        mpi: [mpich, openmpi, intel-oneapi-mpi]
        blas: [openblas]
        lapack: [openblas]
        gl: [osmesa+opengl]
        glx: [osmesa+glx]
        awk: [gawk]
        elf: [elfutils]
        fftw-api: [fftw]
        golang: [gcc]
        iconv: [libiconv]
        java: [openjdk]
        jpeg: [libjpeg-turbo]
        pil: [py-pillow]
        pkgconfig: [pkg-config]
        rpc: [libtirpc]
        scalapack: [netlib-scalapack]
        sycl: [hipsycl]
        szip: [libszip]
        unwind: [libunwind]
        yacc: [bison]
        uuid: [libuuid]
      permissions:
        read: world
        write: user
