  specs:
    # compilers:
    - matrix:
      - [$packages_compilers]
      - [$%compilers_core]
    # Serial: gcc
    - matrix:
      - [$packages_serial_gcc, $mpis_gcc]
      - [$%compilers_gcc]
    # Serial: intel@20+
    - matrix:
      - [$packages_serial_intel, $mpis_intel]
      - [$%compilers_intel]
    #
    # MPI installs: GCC
    - matrix:
      - [$packages_mpi_gcc]
      - [$^mpis_gcc]
      - [$%compilers_gcc]
    # MPI installs: Intel
    - matrix:
      - [$packages_mpi_intel]
      - [$^mpis_intel]
      - [$%compilers_intel]
    #

